name: tokped
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  carousel_slider: ^4.2.1
  cloud_firestore: ^4.3.2
  cupertino_icons: ^1.0.2
  external_app_launcher: ^3.1.0
  firebase_auth: ^4.2.5
  firebase_core: ^2.4.1
  flutter:
    sdk: flutter
  flutter_facebook_auth: ^5.0.7
  flutter_spinkit: ^5.1.0
  get: 4.6.5
  google_sign_in: ^5.4.4
  open_mail_app: ^0.4.5
  pinput: ^2.2.5
  step_progress_indicator: ^1.0.2

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/sp.png
    - assets/images/Facebook.png
    - assets/images/Google.png
    - assets/images/Group 2.png
    - assets/images/Group 20.png
    - assets/images/Group 19.png
    - assets/images/kejuParut.png
    - assets/images/bebasOngkir.png
    - assets/images/kebut.png
    - assets/images/lihatSemua.png
    - assets/images/banggaLokal.png
    - assets/images/cod.png
    - assets/images/elektronik.png
    - assets/images/live.png
    - assets/images/official.png
    - assets/images/promo.png
    - assets/images/seru.png
    - assets/images/toserba.png
    - assets/images/topUp.png
    - assets/images/kejarDiskon.png
    - assets/images/softies.png
    - assets/images/indomie.png
    - assets/images/ceklis.png
    - assets/images/KamisBebasKuman.png
    - assets/images/ohBeauty.png
    - assets/images/megaElectro.png
    - assets/images/mousePad.png
    - assets/images/RainbowMouse.png
    - assets/images/lightspeedMouse.png
    - assets/images/merchant.png
    - assets/images/rivalMouse.png
    - assets/images/tipi.png
    - assets/images/mousePro.png
    - assets/images/colokan.png
    - assets/images/parfum.png
    - assets/images/pp.png
    - assets/images/tatmi.png
    - assets/images/flora.png
    - assets/images/lucid.png
    - assets/images/chanel1.png
    - assets/images/chanel2.png
    - assets/images/chanel3.png
    - assets/images/chanel4.png
    - assets/images/chanelBlur.png
    - assets/images/Rayna.png
    - assets/images/zain.png
