// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCjnocIuypOhzio9ksyrAtpLzqGs4hL1so',
    appId: '1:557344068037:web:6b9dff8d81395df37f3bac',
    messagingSenderId: '557344068037',
    projectId: 're-tokopedia',
    authDomain: 're-tokopedia.firebaseapp.com',
    storageBucket: 're-tokopedia.appspot.com',
    measurementId: 'G-G0KF7V82SN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBom0VvVMyVRk1kgEs5EXEf-62_v5WEMJ8',
    appId: '1:557344068037:android:6113fb96add519297f3bac',
    messagingSenderId: '557344068037',
    projectId: 're-tokopedia',
    storageBucket: 're-tokopedia.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAynmtGGOhMR59zZpVu_XL2aslSKn8Pr1Q',
    appId: '1:557344068037:ios:c18adff990b30b4f7f3bac',
    messagingSenderId: '557344068037',
    projectId: 're-tokopedia',
    storageBucket: 're-tokopedia.appspot.com',
    iosClientId: '557344068037-77hclcjhn6q08j48nad1n0a0e7mhe15o.apps.googleusercontent.com',
    iosBundleId: 'me.company.tokped',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAynmtGGOhMR59zZpVu_XL2aslSKn8Pr1Q',
    appId: '1:557344068037:ios:c18adff990b30b4f7f3bac',
    messagingSenderId: '557344068037',
    projectId: 're-tokopedia',
    storageBucket: 're-tokopedia.appspot.com',
    iosClientId: '557344068037-77hclcjhn6q08j48nad1n0a0e7mhe15o.apps.googleusercontent.com',
    iosBundleId: 'me.company.tokped',
  );
}
